version: '3.3'
services:
    iventoy:
        image: joeclifford/iventoy
        privileged: true
        container_name: iventoy
        restart: unless-stopped
        ports:
            - "67:67/udp"
            - "69:69/tcp"
            - "10809:10809/tcp"
            - "16000:16000/tcp"
            - "26000:26000/tcp"
        volumes:
            - './iso:/opt/iventoy/iso'
            - './data:/opt/iventoy/data'
            - './user:/opt/iventoy/user'