version: '3.3'
services:
    iventoy:
        image: joeclifford/iventoy
        privileged: true
        container_name: iventoy
        network_mode: "host"
        restart: unless-stopped
        volumes:
            - './iso:/opt/iventoy/iso'
            - './data:/opt/iventoy/data'
            - './user:/opt/iventoy/user'